### ISSUE TITLE
Error troubleshooting

### ISSUE THREAD

**Issue by rtavares96** [gact/utl#2]
![image](https://github.com/gact/utl/assets/92459156/5310fd4c-bb98-4fed-9bee-6755672206d0)

**Comment by tw164** [comment]
Hi @rtavares96.. Could you try setting `infiles` to `c('RIL.vcf', 'parents.vcf')` and see if that helps?

**Comment by rtavares96** [comment]
I made the change. Now I am getting this error:

**Warning: ScanVcfParam ‘geno’ fields not found in header: ‘GT’Error in t.default(var.geno$GT) : argument is not a matrix.** 

I did delete the header info besides the required '##fileformat=VCFv4.2' because previous error not finding the header line #CHROM ... 

I tried to add '##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">' line to the header and it did not change anything. 

Here is one line from my parents.vcf:
![image](https://github.com/gact/utl/assets/92459156/73af46bd-4c52-4437-a2b8-478fa2bcf65b)

**Comment by tw164** [comment]
Could you try the following, to see if you can load the sample names using `VariantAnnotation` directly?
```r
library(VariantAnnotation)
file <- 'parents.vcf'
header <- VariantAnnotation::scanVcfHeader(file)
samples <- VariantAnnotation::samples(header)
```

**Comment by tw164** [comment]
I'm going to close this issue due to inactivity. @rtavares96, please get in touch if you feel this needs another look, for example if you continue to see warnings when loading the VCF using `utl` but not when using the `VariantAnnotation` package directly.
